dalia-api/config/routes.rb
Rails.application.routes.draw do
  devise_for :clients

  root to: "home#index"

  resources :clients, only: :show do
    resources :websites
  end

  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'applicants#create'
    end
  end
end

dalia-api/app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :website
  belongs_to :client

  validates :email, presence: true
end

dalia-api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dalia-api/app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :websites
  has_many :applicants
  before_create :generate_api_token

  def primary_website
    websites.first
  end

  private

  def generate_api_token
    self.api_token = SecureRandom.hex
  end
end

dalia-api/app/models/website.rb
class Website < ApplicationRecord
  belongs_to :client
  has_many :applicants
end

dalia-api/app/controllers/api/v1/applicants_controller.rb
module Api
  module V1
    class ApplicantsController < ActionController::API
      def create
        service = ::CreateApplicant.call(
          http_origin: request.env['HTTP_ORIGIN'],
          api_key: params[:api_key],
          email: params[:email]
        )
        return render json: { status: 'ok', applicant_id: service.applicant.id } if service.success?
          
        render json: { status: 'error', message: service.message }, status: :unprocessable_entity
      end
    end
  end
end

dalia-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    return client_websites_url(resource) if resource.is_a?(Client)

    super
  end
end

dalia-api/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def show
  end
end

dalia-api/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

dalia-api/app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :authenticate_client!
  before_action :set_website, only: [:show, :edit, :update, :destroy]
  before_action :set_client, only: [:index, :create, :update, :destroy]

  # GET /clients/:client_id/websites
  def index
    @client = Client.find(params[:client_id])
    @websites = @client.websites
  end

  # GET /clients/:client_id/websites/1
  def show
  end

  # GET /clients/:client_id/websites/new
  def new
    @client = Client.find(params[:client_id])
    @website = @client.websites.build
  end

  # GET /clients/:client_id/websites/1/edit
  def edit
  end

  # POST /clients/:client_id/websites
  def create
    @website = Website.new(website_params)

    if @website.save
      redirect_to client_websites_path(@client), notice: 'Website was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/:client_id/websites/1
  def update
    if @website.update(website_params)
      redirect_to client_websites_path(@client), notice: 'Website was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/:client_id/websites/1
  def destroy
    @website.destroy
    redirect_to client_websites_path(@client), notice: 'Website was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Only allow a trusted parameter "white list" through.
    def website_params
      params.require(:website).permit(:domain).merge(params.permit(:client_id))
    end
end

dalia-api/app/helpers/application_helper.rb
module ApplicationHelper
  def code_snippet(client)
    html_code =
%{<script src="http://cdn.goodniceweb.me/dalia-client.js"></script>
<script>
  window.daliaClient = new DaliaClient.default({
    apiKey: "#{client.api_token}"
  })
</script>}
    CodeRay.scan(html_code, :html).div
  end
end

dalia-api/app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>

dalia-api/app/views/home/index.html.erb
<p><%= link_to('Sign In', new_client_session_path) %></p>
<h1>Boost your hiring process in just 3 simple steps</h1>
<p>1. <%= link_to 'Sign Up', new_client_registration_path %></p>
<p>2. Get code</p>
<p>3. Add to your website</p>

dalia-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DaliaApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

dalia-api/app/views/websites/_form.html.erb
<%= form_with(url: "/clients/#{@client.id}/websites", model: website, local: true) do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
        <% website.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

dalia-api/app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

dalia-api/app/views/websites/index.html.erb
<p><%= link_to('Logout', destroy_client_session_path, method: :delete) %></p>
<h1>Your Websites</h1>

<% if @websites.count.positive? %>
  <p>Please add the following snippet to your website(-s):</p>

  <%= code_snippet(@client).html_safe %>
<% else %>
  <h2>First of all please add your website domain</h2>
<% end %>

<table>
  <thead>
    <tr>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.domain %></td>
        <td><%= link_to 'Edit', edit_client_website_path(@client, website) %></td>
        <td><%= link_to 'Destroy', [@client, website], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_client_website_path %>

dalia-api/app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form', { website: @website, client: @client } %>

<%= link_to 'Back', client_websites_path %>

dalia-api/app/views/websites/show.html.erb
<p>
  <strong>Client:</strong>
  <%= @website.client_id %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @website.domain %>
</p>

<%= link_to 'Edit', edit_client_website_path(@website) %> |
<%= link_to 'Back', websites_path %>